export class CovidInfo {
    iso_code: string;
    continent?: string;
    location: string;
    last_updated_date: Date;
    total_cases?: number;
    new_cases?: number;
    new_cases_smoothed?: number;
    total_deaths?: number;
    new_deaths?: number;
    new_deaths_smoothed?: number;
    total_cases_per_million?: number;
    new_cases_per_million?: number;
    new_cases_smoothed_per_million?: number;
    total_deaths_per_million?: number;
    new_deaths_per_million?: number;
    new_deaths_smoothed_per_million?: number;
    reproduction_rate?: number;
    icu_patients?: number;
    icu_patients_per_million?: number;
    hosp_patients?: number;
    hosp_patients_per_million?: number;
    weekly_icu_admissions?: number;
    weekly_icu_admissions_per_million?: number;
    weekly_hosp_admissions?: number;
    weekly_hosp_admissions_per_million?: number;
    total_tests?: number;
    new_tests?: number;
    total_tests_per_thousand?: number;
    new_tests_per_thousand?: number;
    new_tests_smoothed?: number;
    new_tests_smoothed_per_thousand?: number;
    positive_rate?: number;
    tests_per_case?: number;
    tests_units?: number;
    total_vaccinations?: number;
    people_vaccinated?: number;
    people_fully_vaccinated?: number;
    total_boosters?: number;
    new_vaccinations?: number;
    new_vaccinations_smoothed?: number;
    total_vaccinations_per_hundred?: number;
    people_vaccinated_per_hundred?: number;
    people_fully_vaccinated_per_hundred?: number;
    total_boosters_per_hundred?: number;
    new_vaccinations_smoothed_per_million?: number;
    new_people_vaccinated_smoothed?: number;
    new_people_vaccinated_smoothed_per_hundred?: number;
    stringency_index?: number;
    population?: number;
    population_density?: number;
    median_age?: number;
    aged_65_older?: number;
    aged_70_older?: number;
    gdp_per_capita?: number;
    extreme_poverty?: number;
    cardiovasc_death_rate?: number;
    diabetes_prevalence?: number;
    female_smokers?: number;
    male_smokers?: number;
    handwashing_facilities?: number;
    hospital_beds_per_thousand?: number;
    life_expectancy?: number;
    human_development_index?: number;
    excess_mortality_cumulative_absolute?: number;
    excess_mortality_cumulative?: number;
    excess_mortality?: number;
    excess_mortality_cumulative_per_million?: number;

    constructor() {
        this.iso_code = '';
        this.continent = '';
        this.location = '';
        this.last_updated_date = new Date();
        this.total_cases = 0;
        this.new_cases = 0;
        this.new_cases_smoothed = 0;
        this.total_deaths = 0;
        this.new_deaths = 0;
        this.new_deaths_smoothed = 0;
        this.total_cases_per_million = 0;
        this.new_cases_per_million = 0;
        this.new_cases_smoothed_per_million = 0;
        this.total_deaths_per_million = 0;
        this.new_deaths_per_million = 0;
        this.new_deaths_smoothed_per_million = 0;
        this.reproduction_rate = 0;
        this.icu_patients = 0;
        this.icu_patients_per_million = 0;
        this.hosp_patients = 0;
        this.hosp_patients_per_million = 0;
        this.weekly_icu_admissions = 0;
        this.weekly_icu_admissions_per_million = 0;
        this.weekly_hosp_admissions = 0;
        this.weekly_hosp_admissions_per_million = 0;
        this.total_tests = 0;
        this.new_tests = 0;
        this.total_tests_per_thousand = 0;
        this.new_tests_per_thousand = 0;
        this.new_tests_smoothed = 0;
        this.new_tests_smoothed_per_thousand = 0;
        this.positive_rate = 0;
        this.tests_per_case = 0;
        this.tests_units = 0;
        this.total_vaccinations = 0;
        this.people_vaccinated = 0;
        this.people_fully_vaccinated = 0;
        this.total_boosters = 0;
        this.new_vaccinations = 0;
        this.new_vaccinations_smoothed = 0;
        this.total_vaccinations_per_hundred = 0;
        this.people_vaccinated_per_hundred = 0;
        this.people_fully_vaccinated_per_hundred = 0;
        this.total_boosters_per_hundred = 0;
        this.new_vaccinations_smoothed_per_million = 0;
        this.new_people_vaccinated_smoothed = 0;
        this.new_people_vaccinated_smoothed_per_hundred = 0;
        this.stringency_index = 0;
        this.population = 0;
        this.population_density = 0;
        this.median_age = 0;
        this.aged_65_older = 0;
        this.aged_70_older = 0;
        this.gdp_per_capita = 0;
        this.extreme_poverty = 0;
        this.cardiovasc_death_rate = 0;
        this.diabetes_prevalence = 0;
        this.female_smokers = 0;
        this.male_smokers = 0;
        this.handwashing_facilities = 0;
        this.hospital_beds_per_thousand = 0;
        this.life_expectancy = 0;
        this.human_development_index = 0;
        this.excess_mortality_cumulative_absolute = 0;
        this.excess_mortality_cumulative = 0;
        this.excess_mortality = 0;
        this.excess_mortality_cumulative_per_million = 0;
    }
}